export { SignIn } from './SignIn'
export { ForgetPasswordPage } from './ForgetPasswordPage'
export { ChangePasswordPage } from './ChangePasswordPage'
export { MainPage } from './MainPage'
export { EditProfilePage } from './EditProfilePage'
export { ProfilePage } from './ProfilePage'
export { CatalogPage } from './CatalogPage'