export { SignIn } from './SignIn'
export { ForgetPage } from './ForgetPage'
export { ChangePage } from './ChangePage'
export { MainPage } from './MainPage'
export { EditProfilePage } from './EditProfilePage'